import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";

function validateEmail(email: string) {
  return String(email)
    .toLowerCase()
    .match(
      /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
    );
}

const INITIAL_CONSOLE_TEXT =
  "We can help you achieve your dreams on the information superhighway! Simply enter your email address and give us a brief description of what you need. We'll be in touch sooner than you expect.";

export default function Home() {
  const consoleRef = useRef<HTMLDivElement>(null);

  const [email, setEmail] = useState("");

  const placeCaretAtEnd = (el: HTMLDivElement) => {
    el.focus();
    if (
      typeof window.getSelection != "undefined" &&
      typeof document.createRange != "undefined"
    ) {
      var range = document.createRange();
      range.selectNodeContents(el);
      range.collapse(false);
      var sel = window.getSelection();
      sel?.removeAllRanges();
      sel?.addRange(range);
    }
  };

  const keyDownHandler = (event: KeyboardEvent) => {
    const key = event.key;
    if (key === "Backspace") {
      setEmail((e) => e.slice(0, -1));
      return;
    }
    if (key === "Enter") {
      if (!validateEmail(email)) {
        console.log("ENTER A VALID EMAIL!");
      } else {
        alert(`Email sent to ${email}!`);
      }
      return;
    }

    if (event.key.length === 1) {
      setEmail((e) => e + event.key);
    }
  };

  useEffect(() => {
    if (!consoleRef.current) return;

    console.log = function (message) {
      consoleRef.current!.append("<br />" + message + "<br />>&nbsp;");
      consoleRef.current!.focus();
      placeCaretAtEnd(consoleRef.current!);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <link
          href="https://fonts.cdnfonts.com/css/ocr-a-extended"
          rel="stylesheet"
        ></link>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="layout">
        <div className="header">
          <span></span>
          <a href="Services">work</a>
          <a href="Services">services</a>
          <a href="Services">company</a>
        </div>
        <div className="main">
          <section className="inside_layout">
            <div className="text">
              <h2>ONE STOP SHOP FOR WEB SOLUTIONS</h2>
              <span></span>
              <h3>
                Ready to leave the past behind? Let us create a modern, dynamic
                website for your business.
              </h3>
              <span></span>
              <h1>
                Requirements Gathering: Understanding the client's business
                goals and requirements to determine the scope of the project.
              </h1>
              <h1>
                Design: Creating a visual representation of the website or
                application, including wireframes and mockups.
              </h1>
              <h1>
                Development: Building the website or application using the
                chosen programming languages and frameworks.
              </h1>
              <h1>
                Testing: Ensuring the website or application works as expected
                and meets all of the client's requirements.
              </h1>
              <h1>
                Deployment: Publishing the website or application to the
                client's hosting environment or a public server.
              </h1>
              <h1>
                Maintenance: Ongoing support to ensure the website or
                application continues to function as expected and to make any
                necessary updates or improvements.
              </h1>
              <h1>
                Project Management: Managing the project timeline, resources,
                and communication with the client to ensure a successful
                outcome.
              </h1>
              <h1>
                Quality Assurance: Ensuring that the website or application is
                free of bugs, vulnerabilities, and meets industry standards and
                best practices.
              </h1>
            </div>
            <div className="marginLeft col-lg-3">
              <div className="img-container">
                <Image
                  alt="Picture of the author"
                  src="/Layer 1.png"
                  quality={100}
                  width={506}
                  height={631}
                />
                <div
                  className="positioning"
                  id="console"
                  onFocus={(e) =>
                    (e.target.querySelector("email-input") as any)?.focus?.()
                  }
                >
                  {INITIAL_CONSOLE_TEXT}
                  <div>&gt;&nbsp;</div>
                  <div
                    id="email-input"
                    contentEditable="true"
                    ref={consoleRef}
                    onKeyDown={(e) => keyDownHandler(e as any)}
                  ></div>
                </div>
              </div>
              <div className="behind trapezium"></div>
            </div>
          </section>
        </div>
      </section>
    </>
  );
}
